### ISSUE TITLE
Can't find "SUKL" DataBase 

### ISSUE THREAD

**Issue by rawanaz** [mchaloupka/EVI#30]
I have tried to run your project with the library and i get an error couldn't find the database "SUKL"
because it's running on your Loclhost under windows authentication.
Please help.
Thank you.

**Comment by mchaloupka** [comment]
Hi @rawanaz, thanks for trying the library. First of all, I have to apologize that there is no documentation yet as this project is "work in progress".

Anyway, you don't have an issue with this library, the whole problem is in the [EVI-SampleServer](https://github.com/mchaloupka/EVI-SampleServer) repository. In that repository you can find the `web.config` file where `r2rmlstoreconnection` is configured. You can change it to anything you want. Moreover, there is also `r2rmlConfig` configuration where a path to the R2RML mapping file is configured.

**Comment by mchaloupka** [comment]
I have added this info to the readme.md of the EVI-SampleServer repository. I consider it solved, please write if you have any following questions.

**Comment by rawanaz** [comment]
Thank you for your feedback.
please can i have your sample database and mapping file to test it.

**Comment by mchaloupka** [comment]
@rawanaz The database script can be downloaded from: https://1drv.ms/u/s!Ar31O18jKX66qdBGsa1F28dleTfOhA

The mapping file is the one in the EVI-SampleServer repository.

**Comment by rawanaz** [comment]
Hi Sir,
could I get your email to contact you please, and i'm sure your asking why I want your email, because the things that i'm going to ask you about is not important for github users and i will explain as soon as i get your email.
my email is rawanaz.179@gmail.com if you want to send me yours.
thank you.
